### ISSUE TITLE
Feature Request: Option to Check for Latest Release Candidate (Beta)

### ISSUE THREAD

**Issue by raamdev** [websharks/zencache#352]
It would be nice if a site owner could choose to always run the latest Release Candidate (if available). Whenever we publish a Release Candidate on GitHub, the software (LITE and Pro) could automatically update to that latest beta release if the site owner has this option enabled.

This would help with testing new releases, as a site owner would not need to manually download and install Release Candidates.

For Quick Cache LITE, this could work by monitoring the Quick Cache Releases on GitHub and looking for a new "vXXXXXX (Release Candidate *)" release and downloading and installing the zip file attached to that release.

For Quick Cache Pro, we could utilize the existing update mechanism but have it also look for `quick-cache-pro.vXXXXXX.rc.zip` when this option is enabled.

---

Related: https://github.com/websharks/zencache/issues/395 https://github.com/websharks/zencache/issues/394 https://github.com/websharks/zencache/issues/465 https://github.com/websharks/zencache/issues/289 https://github.com/websharks/zencache/issues/464 https://github.com/websharks/zencache/issues/352

**Comment by jaswrks** [comment]
One portion of this has been completed.

The product API now accepts a `stable` argument that can be set to `0` for the pro version. Setting `stable` to `0` turns off the default value of `1`, and will cause the API to return the latest version (including alpha, beta, RC, etc).

![2015-09-16_05-16-38](https://cloud.githubusercontent.com/assets/1563559/9905634/9882a650-5c32-11e5-8b3b-ae4e0858b1cb.png)
![2015-09-16_05-18-07](https://cloud.githubusercontent.com/assets/1563559/9905633/988234b8-5c32-11e5-90c2-cef70824f04e.png)

**Comment by raamdev** [comment]
Woohoo! 

> and will cause the API to return the latest version (including alpha, beta, RC, etc).

What will determine "the latest version"? Will this just look at the Pro zip files available for download in the zips directory and then take into consideration _any_ pattern after the version number? E.g., `stable=1` will only find `zencache-pro-v150821.zip` whereas with `stable=0` it would instead find `zencache-pro-v150825.rc.zip` (assuming it existed)?

**Comment by jaswrks** [comment]
When `stable=0` all of the zip files are scanned and included as part of a `version_compare()`. The absolute latest version (whether it be stable or not) is returned. See: http://php.net/manual/en/function.version-compare.php

So for instance, if you upload:
- `zencache-pro-v150919.zip`
- `zencache-pro-v150919-rc1.zip`

The latest version (even when `stable=0`) is: `zencache-pro-v150919.zip`

However, if you had the following:
- `zencache-pro-v150919.zip`
- `zencache-pro-v150919-rc1.zip`
- `zencache-pro-v150920-rc.zip`

The latest version (when `stable=0`) is: `zencache-pro-v150920-rc.zip`

If `stable=1` (default behavior), the latest version: `zencache-pro-v150919.zip`

**Comment by raamdev** [comment]
Ah, that makes sense. I thought I might've been missing something when I saw `version_compare()` in the source code. Thanks for explaining. :-)

**Comment by jaswrks** [comment]
## Next Actions (Step 1 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/Plugin.php#L242) add the following:
  
  ``` php
  'pro_update_check_stable',
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/Plugin.php#L378) add the following:
  
  ``` php
  'pro_update_check_stable' => '1', // `0` for beta/RC checks; defaults to `1`
  ```
- After [this line](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/Actions.php#L545) add the following:
  
  ``` php
  'stable' => $this->plugin->options['pro_update_check_stable'],
  ```
- Submit PR.

---

_Referencing the Product API at ZenCache.com: https://github.com/websharks/zencache.com/blob/master/wp-content/mu-plugins/product.php#L606_

**Comment by jaswrks** [comment]
## Next Actions (Step 2 of 2)
- New feature branch in the `websharks/zencache-pro` repo.
- In [this file](https://github.com/websharks/zencache-pro/blob/151004/src/includes/classes/MenuPageProUpdater.php) add a new configurable option to the UI that controls the value of `pro_update_check_stable`, along with any additional details you'd like to add.
  
  _For instance, a select menu that allows a site owner to enable beta and RC releases during an upgrade. If they want to be on the cutting edge at all times, and are willing to accept the risk, they can set `pro_update_check_stable` to a value of `0`._
- Submit PR.

---

**Note:** The above instructions for Step 2 are rather vague. If you're able, attempt step 2 right away. Otherwise, once step 1 is complete hit me on Slack for a more complete set of Step 2 instructions.

**Comment by jaswrks** [comment]
Assigning this to @kristineds :-)

**Comment by kristineds** [comment]
@jaswsinc @raamdev Submitting PRs for Step 1 and 2:
- [Step 1 of 1: Check if running latest RC](https://github.com/websharks/zencache-pro/pull/176)
- [Step 2 of 2: Add new option to update to latest beta release](https://github.com/websharks/zencache-pro/pull/177)

_Note: Step 2 is a work in progress. It is missing a new icon for the menu header and I would probably need some help with the text description.:)_

**Comment by raamdev** [comment]
@jaswsinc One thing I just realized has not yet been addressed is the ability for the Lite version to also check for Beta Updates. I suppose that would require introducing the Pro Updater (minus the stable update portion) to the Lite version, correct? What sorts of challenges do you foresee there?

**Comment by jaswrks** [comment]
> require introducing the Pro Updater (minus the stable update portion) to the Lite version, correct?

Correct. I have not done this yet, so I'm not sure what challenges might exist. However, here are some things that come to mind.
- A possible conflict between the WordPress update servers and our own. I think if beta testing is enabled in the lite version though, that will not matter. Probably not going to be an issue, because the behavior would be opt-in only.
- Not sure what the WordPress update server would respond with it receives a version string that is above and beyond anything that has ever existed on the WordPress.org side; e.g., if you enable beta testing, get the latest/greatest copy, then disable beta testing, and WordPress.org is contacted by the API to compare your current version to the versions available at WordPress.org. Need to test this.

**Comment by raamdev** [comment]
Next Pro Release Changelog:
- **New Feature!** It's now possible to configure the Pro Plugin Updater to check for Beta versions (Release Candidates) of the plugin. See _ZenCache → Plugin Updater → Beta Testers_. We publish Release Candidates a week or so before official releases to allow for additional testing and early preview of upcoming features and bug fixes. If you're not already on our Beta Testers mailing list, you can signup [here](http://zencache.com/r/zencache-beta-testers-list/). Props @kristineds. See [Issue #352](https://github.com/websharks/zencache/issues/352).

**Comment by raamdev** [comment]
I'm forking the work for the Lite version of this feature to a separate GitHub Issue: https://github.com/websharks/zencache/issues/621

**Comment by raamdev** [comment]
**ZenCache Pro v151220** has been released and includes changes worked on as part of this GitHub Issue. See the [release announcement](http://zencache.com/zencache-pro-v151220-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#352).
