### ISSUE TITLE
Post Permalink Changes are not Clearing the Cache File for the Old Permalink

### ISSUE THREAD

**Issue by sarangandk** [websharks/zencache#359]
I found a bug in Quick Cache latest version. When I change permalink for a post and visit the old permalink, that old permalink and the new permalink works and duplicate content. It should delete the old cache and automatically redirect to new permalink without Quick Cache plugin.

To reproduce the error, try the following:
1.) Create a post in WordPress with some random content and publish.
2.) Let's say the permalink for the newly post is http://domain.tld/hello-world.html
3.) Log out from WordPress admin panel and visit http://domain.tld/hello-world.html to get the post cached.
4.) Now login again in WordPress admin panel, edit the post at http://domain.tld/hello-world.html and change the permalink to http://domain.tld/hi-world.html, save the post.
5.) Now logout from admin panel.
6.) Visit http://domain.tld/hello-world.html & http://domain.tld/hi-world.html
7.) Both page will load fine = Duplicate content.

What should have happened is, the cache for the old permalink should have been cleared.

**Comment by raamdev** [comment]
This bug was fixed as part of the work on https://github.com/websharks/zencache/issues/441.

**Comment by raamdev** [comment]
Next release changelog:
- **Bug Fix**: Fixed a bug where changing the permalink for a published post would result in the cache file for the old permalink being left behind and as a result both the old and the new permalink would be accessible, instead of WordPress redirecting the old permalink to the new one. This has been fixed and ZenCache now properly cleared the old cache file when changing the permalink on a published post. [Issue #359](https://github.com/websharks/zencache/issues/359).

**Comment by raamdev** [comment]
This fix has been released with ZenCache v150409:
http://zencache.com/zencache-v150409-now-available/

If you need to follow-up with something related to this GitHub Issue, please open a new GitHub Issue.
