### ISSUE TITLE
Homepage cache not refreshed after posting new post

### ISSUE THREAD

**Issue by baspisa** [websharks/zencache#365]
When I publish a new post it does not show on the homepage when logged out. (Old cache is shown). Page served is not in the browser cache. For me (Lite user) the only option to refresh my homepage is to disable and re-enable the plugin. This behaviour was introduced with version v141110

**Comment by yankustefan** [comment]
Hi, is Quick Cache v141205 still accessible. Or log of the changes made?
I still have 131206 on an WP 3.7.1 and don't have the time to upgrade WP and migrate to Comet Cache.
Thanks for any input.

**Comment by jaswrks** [comment]
@yankustefan I'm afraid not. Quick Cache was recently taken offline at WordPress.org in an effort to avoid confusion and to prevent people from downloading Quick Cache, since it is no longer maintained, in favor of ZenCache or Comet Cache.

However, we do have a release archive available that goes back to the first versions of ZenCache and includes all current versions of the newly renamed Comet Cache plugin. See: https://cometcache.com/release-archive/

**Comment by transasia** [comment]
@jaswsinc Thank you for your reply! I bought another licence, so I can download it, and will try if it works and fixes the problem. Cheers!

**Comment by yankustefan** [comment]
@jaswsinc Thank you for your reply! I bought another licence, so I can download it, and will try if it works and fixes the problem. Cheers!
