### ISSUE TITLE
HTML compression breaks my page

### ISSUE THREAD

**Issue by janrybar** [websharks/zencache#402]
Hi, just bought the PRO version and I really like it! I am aware the HTML compression is just in testing mode, but still - I´d like to ask if a solution could exist.
When I active the html compression (any of its features), it breaks down galleries on my page (http://www.amaze.cz/kurz-fotografovani/) - see the print screens with correct and broke version...

I presume, it is a collision with the gallery plugin called Justified image grid (http://codecanyon.net/item/justified-image-grid-premium-wordpress-gallery/2594251)

Any chance to solve it? Thanks! Jan

![gallery wrong](https://cloud.githubusercontent.com/assets/10613353/5816522/471fa5ee-a0a1-11e4-84cc-16b1bffb0006.png)
![gallery](https://cloud.githubusercontent.com/assets/10613353/5816523/4724ee14-a0a1-11e4-994f-d1d9bf2db2e7.png)

**Comment by raamdev** [comment]
@janrybar Thank you for the report. It's hard to say exactly what is causing the issue here, but I agree we need to test the HTML Compressor more in the wild--your site is a perfect example of that. @jaswsinc, the lead dev on the HTML Compressor portion of Quick Cache, opened a new GitHub Issue under the HTML Compressor repo for us to build a test suite that we can use better test sites like your own (see https://github.com/websharks/html-compressor/issues/53). 

I'm going to leave this issue open until we're better able to test this. For now, I recommend disabling the HTML Compressor in Quick Cache; the other Quick Cache features should continue to work as expected.

**Comment by janrybar** [comment]
Hi,
just a brief addition - I contacted the plugin developer and here is what
he replied: "You could try turning off conditional script loading and the
caching should work. Otherwise, look into "W3 Total Cache" plugin, it's
more widespread and is compatible with JIG. Some caching solutions may
break JS execution too, e.g. re minifying minified content and minfying JS
code which was not meant to be minified, etc."

Can I turn off the conditional script, as he suggested?

Thanks!

Jan

2015-01-20 16:44 GMT+01:00 Raam Dev <notifications@github.com>:

**Comment by raamdev** [comment]
> Can I turn off the conditional script, as he suggested?

I'm not sure what he's referring to by "conditional script loading". Quick Cache doesn't change the order of loading or decide anything conditional about the scripts.

---
You could try figuring out which JS files that plugin is loading and then telling Quick Cache HTML Compressor to exclude those from any compression. That _should_ fix the problem.

![2015-01-28_14-44-06](https://cloud.githubusercontent.com/assets/53005/5945432/5f98fff6-a6fc-11e4-9e4a-85d64c92f05e.png)

Or you might want to try just disabling anything related to JavaScript in the HTML Compressor options.

![2015-01-28_14-43-22](https://cloud.githubusercontent.com/assets/53005/5945440/68f7df22-a6fc-11e4-8c24-201df4a89d2b.png)

**Comment by raamdev** [comment]
I've referenced this issue in https://github.com/websharks/html-compressor/issues/53#issuecomment-125373413, where we're building a test suite for the HTML Compressor to test against sites that are having issues compressing HTML/CSS/JS.

I'm closing this issue in favor of https://github.com/websharks/html-compressor/issues/53.
